# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'About.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutForm(object):
    def setupUi(self, AboutForm):
        AboutForm.setObjectName("AboutForm")
        AboutForm.resize(671, 480)
        AboutForm.setMinimumSize(QtCore.QSize(671, 480))
        AboutForm.setMaximumSize(QtCore.QSize(671, 480))
        AboutForm.setSizeIncrement(QtCore.QSize(671, 480))
        AboutForm.setBaseSize(QtCore.QSize(671, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutForm.setWindowIcon(icon)
        self.L_Tittle = QtWidgets.QLabel(AboutForm)
        self.L_Tittle.setGeometry(QtCore.QRect(130, 20, 421, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.L_Tittle.setFont(font)
        self.L_Tittle.setObjectName("L_Tittle")
        self.L_Updat_eRecord = QtWidgets.QLabel(AboutForm)
        self.L_Updat_eRecord.setGeometry(QtCore.QRect(20, 225, 91, 31))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_Updat_eRecord.setFont(font)
        self.L_Updat_eRecord.setObjectName("L_Updat_eRecord")
        self.textEdit = QtWidgets.QTextEdit(AboutForm)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(30, 260, 611, 211))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.L_About = QtWidgets.QLabel(AboutForm)
        self.L_About.setGeometry(QtCore.QRect(20, 65, 631, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_About.setFont(font)
        self.L_About.setLineWidth(1)
        self.L_About.setWordWrap(True)
        self.L_About.setObjectName("L_About")
        self.L_Author = QtWidgets.QLabel(AboutForm)
        self.L_Author.setGeometry(QtCore.QRect(20, 110, 601, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_Author.setFont(font)
        self.L_Author.setLineWidth(1)
        self.L_Author.setWordWrap(True)
        self.L_Author.setObjectName("L_Author")
        self.L_QQ = QtWidgets.QLabel(AboutForm)
        self.L_QQ.setGeometry(QtCore.QRect(20, 135, 431, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_QQ.setFont(font)
        self.L_QQ.setLineWidth(1)
        self.L_QQ.setWordWrap(True)
        self.L_QQ.setObjectName("L_QQ")
        self.L_WeChat = QtWidgets.QLabel(AboutForm)
        self.L_WeChat.setGeometry(QtCore.QRect(130, 160, 521, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_WeChat.setFont(font)
        self.L_WeChat.setLineWidth(1)
        self.L_WeChat.setWordWrap(True)
        self.L_WeChat.setObjectName("L_WeChat")
        self.L_Github = QtWidgets.QLabel(AboutForm)
        self.L_Github.setGeometry(QtCore.QRect(130, 185, 541, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.L_Github.setFont(font)
        self.L_Github.setLineWidth(1)
        self.L_Github.setWordWrap(True)
        self.L_Github.setOpenExternalLinks(True)
        self.L_Github.setObjectName("L_Github")

        self.retranslateUi(AboutForm)
        QtCore.QMetaObject.connectSlotsByName(AboutForm)

    def retranslateUi(self, AboutForm):
        _translate = QtCore.QCoreApplication.translate
        AboutForm.setWindowTitle(_translate("AboutForm", "关于"))
        self.L_Tittle.setText(_translate("AboutForm", "2Lazy2Write/TooLazyToWrite"))
        self.L_Updat_eRecord.setText(_translate("AboutForm", "更新记录"))
        self.textEdit.setHtml(_translate("AboutForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'等线\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2022.07.01 版本号：0.1-Beta</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">1.增加文本提示</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2.增加联系方式</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">3.增加更新记录</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2022.06.30 版本号：0.1-Canary </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">1.增加了边距边界值（3765×2545）防止程序崩溃</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">2.增加了字号和其他参数的关联，防止程序崩溃</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">3.修复选择的颜色与实际输出颜色不同的Bug</span></p></body></html>"))
        self.L_About.setText(_translate("AboutForm", "基于handright库开发的具有UI界面的手写软件，试图解决在网课环境下大学生不愿意手写的现状"))
        self.L_Author.setText(_translate("AboutForm", "作者：慧木菌（常州大学高分子材料的学生）"))
        self.L_QQ.setText(_translate("AboutForm", "联系方式：QQ：1175592624（备注）"))
        self.L_WeChat.setText(_translate("AboutForm", "WeChat：Y13776834944（自动通过）"))
        self.L_Github.setText(_translate("AboutForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'等线\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Github：<a href=\"https://github.com/1175592624/2Lazy2Write\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/1175592624/2Lazy2Write</span></a></p></body></html>"))
